/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.project.test;

import bitcamp.project.test.service.Heewook;

public class App {
  public String getGreeting() {
    return "Hello world.";
  }

  public static void main(String[] args) {
    System.out.println("-------------------------------------------");
    Heewook h = new Heewook();
    h.list();
    System.out.println("-------------------------------------------");
 
    System.out.println("***********************");
    StudyMemberService sms = new StudyMemberService();
    sms.list();
    System.out.println("***********************");
}
